version: "3.3"
services:
  website:
    build: .
    container_name: website
    ports:
      - 80:80
    networks:
      - internal-1

  message-broker:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - internal-1

networks:
  internal-1:
    external: true
