version: "3.3"
services:
  messages:
    build: .
    container_name: messages
    ports:
      - 8003:80
    depends_on:
      - redis
    networks:
      - messages-1
      - internal-1

  redis:
    image: redis:4.0.2
    networks:
      - messages-1

networks:
  internal-1:
      external: true
  messages-1: