version: "3.3"
services:
  relations:
    build: .
    container_name: relations
    ports:
      - 8002:80
    depends_on:
      - redis
    networks:
      - users_micro-1
      - relations-1

  redis:
    image: redis:4.0.2
    networks:
      - relations-1

networks:
    users_micro-1:
      external: true
    relations-1: