version: "3.3"
services:
  users:
    build: .
    container_name: users
    ports:
      - 8001:80
    depends_on:
      - redis
    networks:
      - micro-1
      - users-1

  redis:
    image: redis:4.0.2
    networks:
      - users-1

networks:
    micro-1:
    users-1: